# This workflow will install Python dependencies and check for broken links
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Manual Pre Checks

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: link-check
      run: |
        pip install -r requirements.txt
        make linkcheck

